package ru.sea.patrol.ws.protocol;

public enum MessageType {

	CHAT_MESSAGE,
	CHAT_JOIN,
	CHAT_LEAVE,
	ROOMS_SNAPSHOT,
	ROOMS_UPDATED,
	PLAYER_INPUT,
	PLAYER_JOIN,
	PLAYER_LEAVE,
	ROOM_JOINED,
	ROOM_JOIN_REJECTED,
	SPAWN_ASSIGNED,
	INIT_GAME_STATE,
	UPDATE_GAME_STATE;
}
